// Famous quotes about patience and time, translated to Vietnamese
const QUOTES = [
  { text: "Kiên nhẫn là đắng, nhưng quả của nó là ngọt.", author: "Aristotle" },
  { text: "Thời gian là thứ quý giá nhất mà con người có thể tiêu xài.", author: "Theophrastus" },
  { text: "Hai thứ quyền lực mạnh nhất trên đời là sự kiên nhẫn và thời gian.", author: "Leo Tolstoy" },
  { text: "Kiên nhẫn không phải là khả năng chờ đợi, mà là cách bạn hành động khi chờ đợi.", author: "Joyce Meyer" },
  { text: "Mỗi khoảnh khắc của sự giận dữ là sáu mươi giây hạnh phúc bị đánh mất.", author: "Ralph Waldo Emerson" },
  { text: "Thời gian chữa lành mọi vết thương.", author: "Tục ngữ" },
  { text: "Hạnh phúc của cuộc sống phụ thuộc vào chất lượng suy nghĩ của bạn.", author: "Marcus Aurelius" },
  { text: "Người kiên nhẫn có thể chờ đợi đúng thời điểm để hành động.", author: "Tục ngữ Nhật Bản" },
  { text: "Không có con đường tắt đến bất kỳ nơi nào đáng để đến.", author: "Beverly Sills" },
  { text: "Thời gian là một người thầy tuyệt vời, nhưng thật đáng tiếc, nó giết chết tất cả học trò của mình.", author: "Hector Berlioz" },
  { text: "Kiên nhẫn, kiên nhẫn, kiên nhẫn. Đó là cách bạn vượt qua.", author: "Walt Whitman" },
  { text: "Chỉ có những người kiên nhẫn mới có thể làm được những việc vĩ đại.", author: "Tục ngữ Ả Rập" },
  { text: "Thời gian trôi qua không ngừng, và chúng ta là những người đi trên nó.", author: "Mahatma Gandhi" },
  { text: "Sự kiên nhẫn là chìa khóa của nội dung.", author: "Tục ngữ Hồi giáo" },
  { text: "Đừng để thời gian kiểm soát bạn. Hãy kiểm soát thời gian của chính mình.", author: "Zig Ziglar" },
  { text: "Một nửa sự lo âu của cuộc đời sẽ biến mất nếu chúng ta nhớ rằng thời gian sẽ luôn trôi qua.", author: "Charles Spurgeon" },
  { text: "Kiên nhẫn là bạn đồng hành của sự khôn ngoan.", author: "Saint Augustine" },
  { text: "Thời gian là tài sản duy nhất mà con người không thể mua được.", author: "Napoleon Bonaparte" },
  { text: "Hành trình ngàn dặm bắt đầu từ một bước chân.", author: "Lão Tử" },
  { text: "Sự kiên nhẫn có giới hạn, và tôi đã đạt đến giới hạn đó.", author: "Tục ngữ" },
  { text: "Đừng bao giờ từ bỏ, vì đó chính là lúc và nơi mà thủy triều sẽ đổi chiều.", author: "Harriet Beecher Stowe" },
  { text: "Thời gian là đồng tiền. Nhưng đồng tiền không thể mua thời gian.", author: "Tục ngữ" },
  { text: "Người biết chờ đợi sẽ nhận được những điều tốt đẹp nhất.", author: "Tục ngữ Việt Nam" },
  { text: "Thời gian không chờ đợi ai, và đó là lý do tại sao chúng ta phải trân trọng từng giây phút.", author: "Khuyết danh" },
  { text: "Kiên nhẫn là phẩm chất cao quý nhất của con người.", author: "Horace" },
  { text: "Cái gì đến sẽ đến, nhưng chỉ với những người kiên nhẫn chờ đợi.", author: "Tục ngữ" },
  { text: "Thời gian là người kể chuyện tốt nhất.", author: "Iris Murdoch" },
  { text: "Sự kiên nhẫn mang lại thành quả xứng đáng.", author: "Tục ngữ Đức" },
  { text: "Mỗi ngày là một cơ hội mới để làm điều gì đó tuyệt vời.", author: "Khuyết danh" },
  { text: "Kiên nhẫn và sự kiên trì có thể thay đổi vận mệnh.", author: "Tục ngữ" }
];
